spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        audit-in:
          destination: audit
          contentType: application/json
        audit-out:
          destination: audit
          contentType: application/json